trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nginx_server: 'root@175.196.233.101'
  nginx_path: '/etc/nginx/conf.d'
  private_key: $(NGINX_PRIVATE_KEY) # 보안을 위해 변수 그룹에서 SSH 개인 키를 설정

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(nginx_server)
    sshPublicKey: $(NGINX_PUBLIC_KEY)
    sshPassphrase: $(NGINX_SSH_PASSPHRASE)
    
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: $(nginx_server)
    sourceFolder: '$(Build.SourcesDirectory)/nginx/conf.d'
    targetFolder: '$(nginx_path)'
    overwrite: true

- script: |
    ssh -i $(private_key) $(nginx_server) 'sudo systemctl restart nginx'
  displayName: 'Restart NGINX'